#!/bin/bash
set -e

PKG_DIR=mutt
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=mutt-1.8.3.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 ftp://ftp.mutt.org/pub/mutt/mutt-1.8.3.tar.gz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/m/$PACKAGE
  fi
fi
MD5="8d1ff7275a3b4fbb0023145abe309cc8  $PACKAGE"


############# Unpacking source
cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
############# Building package
cd $UNPACKDIR

groupadd -g 34 mail
chgrp -v mail /var/mail
cp -v doc/manual.txt{,.shipped} &&
./configure --prefix=/usr                           \
            --sysconfdir=/etc                       \
            --with-docdir=/usr/share/doc/mutt-1.8.3 \
            --enable-external-dotlock               \
            --enable-pop                            \
            --enable-imap                           \
            --enable-hcache                         \
            --enable-sidebar                        &&
make &&
test -s doc/manual.txt || mv -v doc/manual.txt{.shipped,}
make -C doc manual.pdf
make -j1 install
install -v -m644 doc/manual.pdf \
    /usr/share/doc/mutt-1.8.3
ldconfig

cat /usr/share/doc/mutt-1.8.3/samples/gpg.rc >> ~/.muttrc

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || rm -rf $UNPACKDIR unpacked

exit