#!/bin/bash
set -e

export JH_PKG_DIR=openssl10
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=openssl-1.0.2n.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://openssl.org/source/openssl-1.0.2n.tar.gz ||
    wget -T 30 -t 5 ftp://openssl.org/source/openssl-1.0.2n.tar.gz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/o/$PACKAGE
  fi
fi
echo "13bdc1b1d1ff39b6fd42a255e74676a4  $PACKAGE" | md5sum -c -

PATCH=openssl-1.0.2n-compat_versioned_symbols-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/openssl-1.0.2n-compat_versioned_symbols-1.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/o/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $JH_UNPACKDIR
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

 patch -Np1 -i ../openssl-1.0.2n-compat_versioned_symbols-1.patch &&

./config --prefix=/usr            \
         --openssldir=/etc/ssl    \
         --libdir=lib/openssl-1.0 \
         shared                   \
         zlib-dynamic             &&

make depend                       &&
make -j1
#make -k -j1 test || true
make -j1 INSTALL_PREFIX=$PWD/Dest install_sw                      &&

rm -rf /usr/lib/openssl-1.0                                   &&
install -vdm755                   /usr/lib/openssl-1.0        &&
cp -Rv Dest/usr/lib/openssl-1.0/* /usr/lib/openssl-1.0        &&

mv -v  /usr/lib/openssl-1.0/lib{crypto,ssl}.so.1.0.0 /usr/lib &&
ln -sv ../libssl.so.1.0.0         /usr/lib/openssl-1.0        &&
ln -sv ../libcrypto.so.1.0.0      /usr/lib/openssl-1.0        &&

install -vdm755                   /usr/include/openssl-1.0    &&
cp -Rv Dest/usr/include/openssl   /usr/include/openssl-1.0    &&

sed 's@/include$@/include/openssl-1.0@' -i /usr/lib/openssl-1.0/pkgconfig/*.pc

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


ldconfig

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit