#!/bin/bash
set -e

export JH_PKG_DIR=w3m
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=w3m-0.5.3.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://downloads.sourceforge.net/w3m/w3m-0.5.3.tar.gz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/w/$PACKAGE
  fi
fi
echo "1b845a983a50b8dec0169ac48479eacc  $PACKAGE" | md5sum -c -

PATCH=w3m-0.5.3-bdwgc72-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/w3m-0.5.3-bdwgc72-1.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/w/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $JH_UNPACKDIR
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

patch -Np1 -i ../w3m-0.5.3-bdwgc72-1.patch      &&
sed -i 's/file_handle/file_foo/' istream.{c,h}  &&
sed -i 's#gdk-pixbuf-xlib-2.0#& x11#' configure &&
sed -i '/USE_EGD/s/define/undef/' config.h.in   &&


./configure --prefix=/usr --sysconfdir=/etc  &&
make
make -j1 install &&
install -v -m644 -D doc/keymap.default /etc/w3m/keymap &&
install -v -m644    doc/menu.default /etc/w3m/menu &&
install -v -m755 -d /usr/share/doc/w3m-0.5.3 &&
install -v -m644    doc/{HISTORY,READ*,keymap.*,menu.*,*.html} \
                    /usr/share/doc/w3m-0.5.3

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


ldconfig

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit