#!/bin/bash
set -e

export JH_PKG_DIR=apache-ant
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=apache-ant-1.10.2-src.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://archive.apache.org/dist/ant/source/apache-ant-1.10.2-src.tar.xz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/a/$PACKAGE
  fi
fi
echo "57235f3dccfc4b18a260862905ce6c04  $PACKAGE" | md5sum -c -

PACKAGE1=jai-core-1.1.3.jar
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/javax/media/jai-core/1.1.3/jai-core-1.1.3.jar ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/j/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PACKAGE1=jai-codec-1.1.3.jar
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/sun/media/jai-codec/1.1.3/jai-codec-1.1.3.jar ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/j/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PACKAGE1=xz-1.0.jar
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 http://central.maven.org/maven2/org/tukaani/xz/1.0/xz-1.0.jar ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/x/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PACKAGE1=NetRexx-3.06-GA.zip
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 http://www.netrexx.org/files/NetRexx-3.06-GA.zip ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/n/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $JH_UNPACKDIR
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

cp -v ../jai-core-1.1.3.jar  \
      ../jai-codec-1.1.3.jar \
      ../xz-1.0.jar  lib     &&
unzip -p ../NetRexx-3.06-GA.zip lib/NetRexxC.jar > lib/NetRexxC.jar
./bootstrap.sh
bootstrap/bin/ant -f fetch.xml -Ddest=system || true &&
cp -v lib/*.jar lib/optional/
./build.sh -Ddist.dir=$PWD/ant-1.10.2 dist
cp -rv ant-1.10.2 /opt/            &&
chown -R root:root /opt/ant-1.10.2 &&
ln -sfv ant-1.10.2 /opt/ant

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


ldconfig

cat > /etc/profile.d/ant.sh << EOF
# Begin /etc/profile.d/ant.sh

pathappend /opt/ant/bin
export ANT_HOME=/opt/ant

# End /etc/profile.d/ant.sh
EOF

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit