#!/bin/bash
set -e

export JH_PKG_DIR=texlive
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=texlive-20170524-source.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 ftp://tug.org/texlive/historic/2017/texlive-20170524-source.tar.xz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PACKAGE
  fi
fi
echo "f98f6bde0a2c20fc894d983d542beaad  $PACKAGE" | md5sum -c -

PACKAGE1=texlive-20170524-texmf.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 ftp://tug.org/texlive/historic/2017/texlive-20170524-texmf.tar.xz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PACKAGE1
  fi
fi
echo "44bb5d71fc64ac90118f8c5013e39b89  $PACKAGE1" | md5sum -c -
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PATCH=texlive-20170524-source-gcc7-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/texlive-20170524-source-gcc7-1.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR

PATCH=texlive-20170524-source-upstream_fixes-2.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/texlive-20170524-source-upstream_fixes-2.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR

PATCH=texlive-20170524-source-poppler059-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/texlive-20170524-source-poppler059-1.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR

PATCH=texlive-20170524-texmf-upstream_fixes-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PATCH ]] ; then
    cp $JH_SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/texlive-20170524-texmf-upstream_fixes-1.patch ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/t/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $JH_UNPACKDIR
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

cat >> /etc/ld.so.conf << EOF
# Begin texlive 2017 addition

/opt/texlive/2017/lib

# End texlive 2017 addition
EOF

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


export TEXARCH=$(uname -m | sed -e 's/i.86/i386/' -e 's/$/-linux/') &&

patch -Np1 -i ../texlive-20170524-source-gcc7-1.patch           &&
patch -Np1 -i ../texlive-20170524-source-upstream_fixes-2.patch &&
patch -Np1 -i ../texlive-20170524-source-poppler059-1.patch     &&

mkdir texlive-build &&
cd texlive-build    &&

../configure                                                    \
    --prefix=/opt/texlive/2017                                  \
    --bindir=/opt/texlive/2017/bin/$TEXARCH                     \
    --datarootdir=/opt/texlive/2017                             \
    --includedir=/opt/texlive/2017/include                      \
    --infodir=/opt/texlive/2017/texmf-dist/doc/info             \
    --libdir=/opt/texlive/2017/lib                              \
    --mandir=/opt/texlive/2017/texmf-dist/doc/man               \
    --disable-native-texlive-build                              \
    --disable-static --enable-shared                            \
    --with-system-cairo                                         \
    --with-system-fontconfig                                    \
    --with-system-freetype2                                     \
    --with-system-gmp                                           \
    --with-system-graphite2                                     \
    --with-system-harfbuzz                                      \
    --with-system-icu                                           \
    --with-system-libgs                                         \
    --with-system-libpaper                                      \
    --with-system-libpng                                        \
    --with-system-mpfr                                          \
    --with-system-pixman                                        \
    --with-system-poppler                                       \
    --with-system-xpdf                                          \
    --with-system-zlib                                          \
    --with-banner-add=" - BLFS" &&

make
#make -k check || true
make -j1 install-strip &&
/sbin/ldconfig &&
make -j1 texlinks &&
mkdir -pv /opt/texlive/2017/tlpkg/TeXLive/ &&
install -v -m644 ../texk/tests/TeXLive/* /opt/texlive/2017/tlpkg/TeXLive/
tar -xf ../../texlive-20170524-texmf.tar.xz -C /opt/texlive/2017 --strip-components=1 &&
pushd /opt/texlive/2017 &&
patch -Np1 -i /sources/texlive-20170524-texmf-upstream_fixes-1.patch &&
popd
mktexlsr &&
fmtutil-sys --all &&
mtxrun --generate

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


ldconfig

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit