#!/bin/bash
set -e

export JH_PKG_DIR=fuse2
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=fuse-2.9.7.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://github.com/libfuse/libfuse/releases/download/fuse-2.9.7/fuse-2.9.7.tar.gz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/f/$PACKAGE
  fi
fi
echo "9bd4ce8184745fd3d000ca2692adacdb  $PACKAGE" | md5sum -c -


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $JH_UNPACKDIR
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

./configure --prefix=/usr    \
            --disable-static \
            --exec-prefix=/  &&

make &&
make DESTDIR=$PWD/Dest install
install -vm755 Dest/lib/libfuse.so.2.9.7 /lib                  &&
install -vm755 Dest/lib/libulockmgr.so.1.0.1 /lib                 &&
ln -sfv ../../lib/libfuse.so.2.9.7 /usr/lib/libfuse.so         &&
ln -sfv ../../lib/libulockmgr.so.1.0.1 /usr/lib/libulockmgr.so &&

install -vm644  Dest/lib/pkgconfig/fuse.pc /usr/lib/pkgconfig  && 
                                                         
install -vm4755 Dest/bin/fusermount       /bin                 &&
install -vm755  Dest/bin/ulockmgr_server  /bin                 &&

install -vm755  Dest/sbin/mount.fuse      /sbin                &&

install -vdm755 /usr/include/fuse                              &&

install -vm644  Dest/usr/include/*.h      /usr/include         &&
install -vm644  Dest/usr/include/fuse/*.h /usr/include/fuse/   &&

install -vm644  Dest/usr/share/man/man1/* /usr/share/man/man1  &&
/sbin/ldconfig -v

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la ! -path \*ImageMagick\* -delete
done


ldconfig

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit